#!/bin/bash
FILE1=$(file -b $1)

if [[ $FILE1 == *Zip* ]]; then
    unzip $1

elif [[ $FILE1 == *tar* ]]; then
    tar -xvf $1

elif [[ $FILE1 == *gzip* ]]; then
    tar -zxvf $1

elif [[ $FILE1 == *bzip2* ]]; then
    tar -jxvf $1

elif [[ $FILE1 == *7-zip* ]]; then
    7z e $1

elif [[ $FILE1 == *XZ* ]]; then
    xz -d $1

else
    echo "You are trying to decompress an unsupported file"
fi
